// [dial code, ISO-3166 alpha-2, English name]
export type Country = { dial: string; iso: string; name: string };

const RAW: [string, string, string][] = [
  ["91", "IN", "India"],
  ["1", "US", "United States"],
  ["44", "GB", "United Kingdom"],
  ["971", "AE", "United Arab Emirates"],
  ["61", "AU", "Australia"],
  ["1", "CA", "Canada"],
  ["65", "SG", "Singapore"],
  ["966", "SA", "Saudi Arabia"],
  ["60", "MY", "Malaysia"],
  ["64", "NZ", "New Zealand"],
  ["977", "NP", "Nepal"],
  ["94", "LK", "Sri Lanka"],
  ["880", "BD", "Bangladesh"],
  ["92", "PK", "Pakistan"],
  ["93", "AF", "Afghanistan"],
  ["355", "AL", "Albania"],
  ["213", "DZ", "Algeria"],
  ["376", "AD", "Andorra"],
  ["244", "AO", "Angola"],
  ["54", "AR", "Argentina"],
  ["374", "AM", "Armenia"],
  ["43", "AT", "Austria"],
  ["994", "AZ", "Azerbaijan"],
  ["973", "BH", "Bahrain"],
  ["375", "BY", "Belarus"],
  ["32", "BE", "Belgium"],
  ["229", "BJ", "Benin"],
  ["975", "BT", "Bhutan"],
  ["591", "BO", "Bolivia"],
  ["387", "BA", "Bosnia and Herzegovina"],
  ["267", "BW", "Botswana"],
  ["55", "BR", "Brazil"],
  ["673", "BN", "Brunei"],
  ["359", "BG", "Bulgaria"],
  ["226", "BF", "Burkina Faso"],
  ["257", "BI", "Burundi"],
  ["855", "KH", "Cambodia"],
  ["237", "CM", "Cameroon"],
  ["238", "CV", "Cape Verde"],
  ["236", "CF", "Central African Republic"],
  ["235", "TD", "Chad"],
  ["56", "CL", "Chile"],
  ["86", "CN", "China"],
  ["57", "CO", "Colombia"],
  ["242", "CG", "Congo"],
  ["243", "CD", "Congo (DRC)"],
  ["506", "CR", "Costa Rica"],
  ["225", "CI", "Côte d'Ivoire"],
  ["385", "HR", "Croatia"],
  ["53", "CU", "Cuba"],
  ["357", "CY", "Cyprus"],
  ["420", "CZ", "Czechia"],
  ["45", "DK", "Denmark"],
  ["253", "DJ", "Djibouti"],
  ["593", "EC", "Ecuador"],
  ["20", "EG", "Egypt"],
  ["503", "SV", "El Salvador"],
  ["291", "ER", "Eritrea"],
  ["372", "EE", "Estonia"],
  ["251", "ET", "Ethiopia"],
  ["679", "FJ", "Fiji"],
  ["358", "FI", "Finland"],
  ["33", "FR", "France"],
  ["241", "GA", "Gabon"],
  ["220", "GM", "Gambia"],
  ["995", "GE", "Georgia"],
  ["49", "DE", "Germany"],
  ["233", "GH", "Ghana"],
  ["30", "GR", "Greece"],
  ["502", "GT", "Guatemala"],
  ["224", "GN", "Guinea"],
  ["592", "GY", "Guyana"],
  ["509", "HT", "Haiti"],
  ["504", "HN", "Honduras"],
  ["852", "HK", "Hong Kong"],
  ["36", "HU", "Hungary"],
  ["354", "IS", "Iceland"],
  ["62", "ID", "Indonesia"],
  ["98", "IR", "Iran"],
  ["964", "IQ", "Iraq"],
  ["353", "IE", "Ireland"],
  ["972", "IL", "Israel"],
  ["39", "IT", "Italy"],
  ["81", "JP", "Japan"],
  ["962", "JO", "Jordan"],
  ["7", "KZ", "Kazakhstan"],
  ["254", "KE", "Kenya"],
  ["965", "KW", "Kuwait"],
  ["996", "KG", "Kyrgyzstan"],
  ["856", "LA", "Laos"],
  ["371", "LV", "Latvia"],
  ["961", "LB", "Lebanon"],
  ["266", "LS", "Lesotho"],
  ["231", "LR", "Liberia"],
  ["218", "LY", "Libya"],
  ["423", "LI", "Liechtenstein"],
  ["370", "LT", "Lithuania"],
  ["352", "LU", "Luxembourg"],
  ["853", "MO", "Macao"],
  ["261", "MG", "Madagascar"],
  ["265", "MW", "Malawi"],
  ["960", "MV", "Maldives"],
  ["223", "ML", "Mali"],
  ["356", "MT", "Malta"],
  ["222", "MR", "Mauritania"],
  ["230", "MU", "Mauritius"],
  ["52", "MX", "Mexico"],
  ["373", "MD", "Moldova"],
  ["377", "MC", "Monaco"],
  ["976", "MN", "Mongolia"],
  ["382", "ME", "Montenegro"],
  ["212", "MA", "Morocco"],
  ["258", "MZ", "Mozambique"],
  ["95", "MM", "Myanmar"],
  ["264", "NA", "Namibia"],
  ["31", "NL", "Netherlands"],
  ["505", "NI", "Nicaragua"],
  ["227", "NE", "Niger"],
  ["234", "NG", "Nigeria"],
  ["850", "KP", "North Korea"],
  ["389", "MK", "North Macedonia"],
  ["47", "NO", "Norway"],
  ["968", "OM", "Oman"],
  ["680", "PW", "Palau"],
  ["970", "PS", "Palestine"],
  ["507", "PA", "Panama"],
  ["675", "PG", "Papua New Guinea"],
  ["595", "PY", "Paraguay"],
  ["51", "PE", "Peru"],
  ["63", "PH", "Philippines"],
  ["48", "PL", "Poland"],
  ["351", "PT", "Portugal"],
  ["974", "QA", "Qatar"],
  ["40", "RO", "Romania"],
  ["7", "RU", "Russia"],
  ["250", "RW", "Rwanda"],
  ["685", "WS", "Samoa"],
  ["378", "SM", "San Marino"],
  ["221", "SN", "Senegal"],
  ["381", "RS", "Serbia"],
  ["248", "SC", "Seychelles"],
  ["232", "SL", "Sierra Leone"],
  ["421", "SK", "Slovakia"],
  ["386", "SI", "Slovenia"],
  ["252", "SO", "Somalia"],
  ["27", "ZA", "South Africa"],
  ["82", "KR", "South Korea"],
  ["211", "SS", "South Sudan"],
  ["34", "ES", "Spain"],
  ["249", "SD", "Sudan"],
  ["597", "SR", "Suriname"],
  ["268", "SZ", "Eswatini"],
  ["46", "SE", "Sweden"],
  ["41", "CH", "Switzerland"],
  ["963", "SY", "Syria"],
  ["886", "TW", "Taiwan"],
  ["992", "TJ", "Tajikistan"],
  ["255", "TZ", "Tanzania"],
  ["66", "TH", "Thailand"],
  ["228", "TG", "Togo"],
  ["676", "TO", "Tonga"],
  ["216", "TN", "Tunisia"],
  ["90", "TR", "Türkiye"],
  ["993", "TM", "Turkmenistan"],
  ["256", "UG", "Uganda"],
  ["380", "UA", "Ukraine"],
  ["598", "UY", "Uruguay"],
  ["998", "UZ", "Uzbekistan"],
  ["58", "VE", "Venezuela"],
  ["84", "VN", "Vietnam"],
  ["967", "YE", "Yemen"],
  ["260", "ZM", "Zambia"],
  ["263", "ZW", "Zimbabwe"],
];

export const COUNTRIES: Country[] = RAW.map(([dial, iso, name]) => ({ dial, iso, name }));

export const DEFAULT_COUNTRY = COUNTRIES[0]; // India

/** ISO-3166 alpha-2 → flag emoji, via regional indicator symbols. */
export function flagOf(iso: string) {
  return String.fromCodePoint(...[...iso.toUpperCase()].map((c) => 127397 + c.charCodeAt(0)));
}
